name: Wayback Machine
description: Save the provided sites to the Wayback Machine at archive.org

inputs:
  source:
    description: The site handle to screenshot
    required: true
  access-key:
    description: An API key with permission to post to archive.org
    required: true
  secret-key:
    description: An API secret with permission to post to archive.org
    required: true

runs:
  using: "composite"
  steps:
    - id: install
      name: Install Python dependencies
      uses: ./.github/actions/install

    - id: save-page
      name: Save in Wayback Machine
      run: newshomepages-wayback ${{ inputs.source }} -o _dist
      shell: bash
      env:
        IA_ACCESS_KEY: ${{ inputs.access-key }}
        IA_SECRET_KEY: ${{ inputs.secret-key }}

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: wayback
        path: _dist
        if-no-files-found: error
