name: Wayback
description: Submit URL to archive.org's Wayback Machine

inputs:
  source:
    description: The source to archive
    required: true
  access-key:
    description: An API key with permission to post to archive.org
    required: true
  secret-key:
    description: An API secret with permission to post to archive.org
    required: true

runs:
  using: 'composite'
  steps:
    - id: ping-wayback
      name: Save in Wayback Machine
      run: pipenv run newshomepages-wayback ${{ inputs.source }} -o _dist
      shell: bash
      env:
        IA_ACCESS_KEY: ${{ inputs.access-key }}
        IA_SECRET_KEY: ${{ inputs.secret-key }}