name: Accessibility
description: Download the a11y tree for the provided site

inputs:
  source:
    description: The site handle to screenshot
    required: true

runs:
  using: "composite"
  steps:
    - id: install
      name: Install Python dependencies
      uses: ./.github/actions/install

    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run shot-scraper install
      shell: bash

    - id: parse-a11y
      name: Parse accessibility tree JSON
      run: pipenv run newshomepages-accessibility ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: accessibility
        path: _dist
        if-no-files-found: error
