name: Screenshot
description: Take a screenshot of the provided site

inputs:
  source:
    description: The command config spelling out what to screenshot
    required: true
  artifact:
    description: The name of the artifact to upload
    required: false
    default: screenshots

runs:
  using: 'composite'
  steps:
    - id: install
      name: Install Python dependencies
      uses: ./.github/actions/install

    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run playwright install --with-deps chromium
      shell: bash

    - id: shoot
      name: Take screenshot
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run newshomepages-screenshot ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact }}
        path: _dist
        if-no-files-found: error