name: ads.txt
description: Download ads.txt from a site

inputs:
  source:
    description: The source to archive
    required: true

runs:
  using: 'composite'
  steps:
    - id: ads-txt
      name: Download ads.txt
      run: pipenv run newshomepages-adstxt ${{ inputs.source }} -o _dist --verbose
      shell: bash