name: Download items
description: Download items from our archive.org collection

inputs:
  command:
    description: The command to run
    required: true
  collection:
    description: The identifier of the target archive.org collection
    required: true

runs:
  using: 'composite'
  steps:
    - id: download
      name: Download
      run: pipenv run newshomepages-extract download-items ${{ inputs.command }} --output-path ./_items
      shell: bash
      env:
        IA_COLLECTION: ${{ inputs.collection }}

    - id: save-items
      name: Save items artifact
      uses: actions/upload-artifact@v3
      with:
        name: items
        path: ./_items/*.json
        if-no-files-found: warn
