name: Download items
description: Download items from our archive.org collection

inputs:
  command:
    description: The command to run
    required: true
  access-key:
    description: An API key with permission to post to archive.org
    required: true
  secret-key:
    description: An API secret with permission to post to archive.org
    required: true
  collection:
    description: The identifier of the target archive.org collection
    required: true

runs:
  using: 'composite'
  steps:
    - id: download
      name: Download
      run: pipenv run newshomepages-extract items ${{ inputs.command }} --output-dir ./_items
      shell: bash
      env:
        IA_COLLECTION: ${{ inputs.collection }}

    - id: upload-latest
      name: Upload file to archive.org
      uses: palewire/internet-archive-upload@main
      with:
        access-key: ${{ inputs.access-key }}
        secret-key: ${{ inputs.secret-key }}
        identifier: latest-homepages
        files: ./_items/

    - id: save-items
      name: Save items artifact
      uses: actions/upload-artifact@v3
      with:
        name: items
        path: ./_items/*.json
        if-no-files-found: warn
