name: Upload
description: Upload the provided artifact to Amazon S3

inputs:
  artifact:
    description: The name of the artifact to upload
    required: true
  destination:
    description: The bucket folder where the artifact should be uploaded
    required: true
  s3-access-key-id:
    description: An API key with permission to post to Amazon S3
    required: true
  s3-secret-access-key:
    description: An API secret with permission to post to Amazon S3
    required: true
  s3-bucket-name:
    description: The identifier of the target Amazon S3 bucket
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact }}
        path: './${{ inputs.destination }}'

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ inputs.s3-access-key-id }}
        aws_secret_access_key: ${{ inputs.s3-secret-access-key }}
        aws_bucket: ${{ inputs.s3-bucket-name }}
        source_dir: './${{ inputs.destination }}/'
        destination_dir: './${{ inputs.destination }}/'