name: robots.txt
description: Download robots.txt from a site

inputs:
  source:
    description: The source to archive
    required: true

runs:
  using: 'composite'
  steps:
    - id: robots-txt
      name: Download robots.txt
      run: pipenv run newshomepages-robotstxt ${{ inputs.source }} -o _dist --verbose
      shell: bash