name: Telegram
description: Post to Telegram

inputs:
  command:
    description: "The command to run"
    required: true
  api-key:
    description: An API key with permission to post to Telegram
    required: true

runs:
  using: "composite"
  steps:
    - id: telegram
      name: Telegram
      run: pipenv run python -m newshomepages.telegrammer ${{ inputs.command }}
      shell: bash
      env:
        TELEGRAM_API_KEY: ${{ inputs.api-key }}
