name: Batch
description: Return a batch of site handles as JSON

inputs:
  command:
    description: The batch command to run
    required: true
outputs:
  site-list:
    description: A list of site handles
    value: ${{ steps.set-output.outputs.site-list }}

runs:
  using: 'composite'
  steps:
    - id: install
      name: Install Python dependencies
      uses: ./.github/actions/install

    - id: create-json
      name: Create JSON
      run: pipenv run newshomepages-batch ${{ inputs.command }} > sites.json
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: sites
        path: sites.json
        if-no-files-found: error

    - id: set-output
      name: Output site list
      run: echo "::set-output name=site-list::$(cat sites.json | jq -c)"
      shell: bash
