name: Hyperlinks
description: Extract hyperlinks from the page

inputs:
  source:
    description: The source to collect
    required: true

runs:
  using: 'composite'
  steps:
    - id: get-hyperlinks
      name: Get hyperlinks
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run newshomepages-hyperlinks ${{ inputs.source }} -o _dist --verbose
      shell: bash