name: Hyperlinks
description: Download all hyperlinks on a site

inputs:
  source:
    description: The site handle to screenshot
    required: true

runs:
  using: "composite"
  steps:
    - id: install
      name: Install Python dependencies
      uses: ./.github/actions/install

    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run playwright install --with-deps chromium
      shell: bash

    - id: parse-json
      name: Parse out hyperlinks
      run: pipenv run newshomepages-hyperlinks ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: hyperlinks
        path: _dist
        if-no-files-found: error
