name: Screenshot (full page)
description: Take a full-page screenshot of the provided source

inputs:
  source:
    description: The source to collect
    required: true

runs:
  using: 'composite'
  steps:
    - id: shoot-full-page-screenshot
      name: Take full-page screenshot
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run newshomepages-screenshot ${{ inputs.source }} --full-page -o _dist --verbose
      shell: bash

    - id: save-full-page-screenshot
      name: Save full-page screenshot artifact
      uses: actions/upload-artifact@v3
      with:
        name: full-page-screenshots
        path: ./_dist/${{ inputs.source }}.fullpage.jpg
        if-no-files-found: warn
