name: Screenshot (full page)
description: Take a full-page screenshot of the provided source

inputs:
  source:
    description: The source to collect
    required: true

runs:
  using: 'composite'
  steps:
    - id: shoot-full-page-screenshot
      name: Take full-page screenshot
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run newshomepages-screenshot ${{ inputs.source }} --full-page -o _dist --verbose
      shell: bash
      env:
        PW_TEST_SCREENSHOT_NO_FONTS_READY: 1
