
name: Discord
description: Post screenshots to a Discord channel

inputs:
  command:
    description: The Discord command to run
    required: true
  bot-token:
    description: A bot token with permission to post to Discord
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: mosaics
        path: ./_input

    - id: discord
      name: Discord
      run: pipenv run newshomepages-discorder ${{ inputs.command }} -i ./_input
      shell: bash
      env:
        DISCORD_BOT_TOKEN: ${{ inputs.bot-token }}