
name: Discord
description: Post to Discord

inputs:
  command:
    description: The Discord command to run
    required: true
  bot-token:
    description: A bot token with permission to post to Discord
    required: true

runs:
  using: "composite"
  steps:
    - id: discord
      name: Discord
      run: pipenv run newshomepages-discorder ${{ inputs.command }}
      shell: bash
      env:
        DISCORD_BOT_TOKEN: ${{ inputs.bot-token }}