name: HTML
description: Save the site's full HTML

inputs:
  source:
    description: The source to archive
    required: true

runs:
  using: 'composite'
  steps:
    - id: html
      name: Fetch HTML
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run python -m newshomepages.html ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: html
        path: _dist/${{ inputs.source }}.html
        if-no-files-found: warn