name: 'Scheduled Archive: All sites (Batch 2)'

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22,10 * * *"

jobs:
  archive-batch:
    name: Archive batch
    uses: palewire/news-homepages-runner/.github/workflows/reusable-archive-batch.yaml@main
    with:
      batch: 2
    secrets: inherit
