name: 'Archive a bundle'

on:
  workflow_dispatch:
    inputs:
      bundle:
        description: 'Bundle slug'
        required: true
        type: string

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages-runner/.github/workflows/reusable-archive-bundle.yaml@main
    with:
      bundle: ${{ inputs.bundle }}
    secrets: inherit