name: 'Scheduled Archive: All sites (Batch 3)'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23,11 * * *"

jobs:
  archive-batch:
    name: Archive batch
    uses: palewire/news-homepages-runner/.github/workflows/reusable-archive-batch.yaml@main
    with:
      batch: 3
    secrets: inherit
