name: 'Scheduled Archive: All sites (Batch 5)'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0,12 * * *"

jobs:
  archive-batch:
    name: Archive batch
    uses: palewire/news-homepages-runner/.github/workflows/reusable-archive-batch.yaml@main
    with:
      batch: 5
    secrets: inherit
