name: 'Scheduled Archive: All sites (Batch 9)'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2,14 * * *"

jobs:
  archive-batch:
    name: Archive batch
    uses: palewire/news-homepages-runner/.github/workflows/reusable-archive-batch.yaml@main
    with:
      batch: 9
    secrets: inherit
