name: 'Scheduled Archive: All sites (Batch 8)'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "30 1,13 * * *"

jobs:
  archive-batch:
    name: Archive batch
    uses: palewire/news-homepages-runner/.github/workflows/reusable-archive-batch.yaml@main
    with:
      batch: 8
    secrets: inherit
