name: 'Reusable workflow: Archive country'

on:
  workflow_call:
    inputs:
      country:
        description: The two-digit alpha code of the country to archive
        required: true
        type: string

jobs:
  sources:
    name: Sources
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: get-site-list
        uses: ./.github/actions/batch
        with:
          command: sites-by-country ${{ inputs.country }}
    outputs:
      site-list: ${{ steps.get-site-list.outputs.site-list }}

  archive:
    name: Archive
    runs-on: ubuntu-latest
    needs: sources
    timeout-minutes: 60
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        source: ${{ fromJson(needs.sources.outputs.site-list) }}
    steps:
      - id: checkout
        name: Checkout
        timeout-minutes: 5
        uses: actions/checkout@v3

      - id: install
        timeout-minutes: 5
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: mk-dist-dir
        name: Create distribution directory
        run: mkdir _dist
        shell: bash

      - id: screenshot-cropped
        name: Screenshot (cropped)
        timeout-minutes: 5
        uses: ./.github/actions/screenshot-cropped
        with:
          source: ${{ matrix.source }}

      - id: hyperlinks
        name: Hyperlinks
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/hyperlinks
        with:
          source: ${{ matrix.source }}

      - id: accessibility
        name: Accessibility tree
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/accessibility
        with:
          source: ${{ matrix.source }}

      - id: wayback
        name: Wayback Machine
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/wayback
        with:
          source: ${{ matrix.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}

      - id: robotstxt
        name: robots.txt
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/robotstxt
        with:
          source: ${{ inputs.source }}

      - id: lighthouse
        name: Lighthouse
        if: ${{ always() }}
        timeout-minutes: 10
        uses: ./.github/actions/lighthouse
        with:
          source: ${{ matrix.source }}

      - id: archive
        name: Archive
        if: ${{ always() }}
        timeout-minutes: 10
        uses: ./.github/actions/archive
        with:
          source: ${{ matrix.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          collection: ${{ secrets.IA_COLLECTION }}

      - id: download-items
        name: Download items
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/download-items
        with:
          command: ${{ matrix.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          collection: ${{ secrets.IA_COLLECTION }}

  post:
    name: Post
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: archive
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - uses: actions/download-artifact@v3
        with:
          name: screenshots
          path: ./_input

      - id: mosaic
        name: Mosaic
        uses: ./.github/actions/mosaic
        with:
          command: jpg -i ./_input/

      - id: discord
        name: Discord
        uses: ./.github/actions/discord
        if: ${{ always() }}
        with:
          command: country ${{ inputs.country }} -i ./_input/
          bot-token: ${{ secrets.DISCORD_BOT_TOKEN }}

      - id: telegram
        name: Telegram
        uses: ./.github/actions/telegram
        if: ${{ always() }}
        with:
          command: country ${{ inputs.country }} -i ./_input/
          api-key: ${{ secrets.TELEGRAM_API_KEY }}
