name: 'Reusable workflow: Archive single site'

on:
  workflow_call:
    inputs:
      source:
        description: The handle of the site to archive
        required: true
        type: string

jobs:
  archive:
    name: Archive
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - id: checkout
        name: Checkout
        timeout-minutes: 5
        uses: actions/checkout@v3

      - id: install
        timeout-minutes: 5
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: mk-dist-dir
        name: Create distribution directory
        run: mkdir _dist
        shell: bash

      - id: screenshot-cropped
        name: Screenshot (cropped)
        timeout-minutes: 5
        uses: ./.github/actions/screenshot-cropped
        with:
          source: ${{ inputs.source }}

      - id: hyperlinks
        name: Hyperlinks
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/hyperlinks
        with:
          source: ${{ inputs.source }}

      - id: accessibility
        name: Accessibility tree
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/accessibility
        with:
          source: ${{ inputs.source }}

      - id: wayback
        name: Wayback Machine
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/wayback
        with:
          source: ${{ inputs.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}

      - id: lighthouse
        name: Lighthouse
        if: ${{ always() }}
        timeout-minutes: 10
        uses: ./.github/actions/lighthouse
        with:
          source: ${{ inputs.source }}

      - id: archive
        name: Archive
        if: ${{ always() }}
        timeout-minutes: 10
        uses: ./.github/actions/archive
        with:
          source: ${{ inputs.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          collection: ${{ secrets.IA_COLLECTION }}

      - id: download-items
        name: Download items
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/download-items
        with:
          command: ${{ inputs.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          collection: ${{ secrets.IA_COLLECTION }}
