name: 'Reusable workflow: Archive bundle'

on:
  workflow_call:
    inputs:
      bundle:
        description: The slug of the bundle to archive
        required: true
        type: string

jobs:
  sources:
    name: Sources
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: get-site-list
        uses: ./.github/actions/batch
        with:
          command: sites-by-bundle ${{ inputs.bundle }}
    outputs:
      site-list: ${{ steps.get-site-list.outputs.site-list }}

  archive:
    name: Archive
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: sources
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        source: ${{ fromJson(needs.sources.outputs.site-list) }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: mk-dist-dir
        name: Create distribution directory
        run: mkdir _dist
        shell: bash

      - id: screenshot-cropped
        name: Screenshot (cropped)
        timeout-minutes: 5
        uses: ./.github/actions/screenshot-cropped
        with:
          source: ${{ matrix.source }}

      - id: screenshot-full-page
        name: Screenshot (full page)
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/screenshot-full-page
        with:
          source: ${{ matrix.source }}

      - id: hyperlinks
        name: Hyperlinks
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/hyperlinks
        with:
          source: ${{ matrix.source }}

      - id: accessibility
        name: Accessibility tree
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/accessibility
        with:
          source: ${{ matrix.source }}

      - id: wayback
        name: Wayback Machine
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/wayback
        with:
          source: ${{ matrix.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}

      - id: lighthouse
        name: Lighthouse
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/lighthouse
        with:
          source: ${{ matrix.source }}

      - id: html
        name: HTML
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/html
        with:
          source: ${{ matrix.source }}

      - id: archive
        name: Archive
        if: ${{ always() }}
        timeout-minutes: 5
        uses: ./.github/actions/archive
        with:
          source: ${{ matrix.source }}
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          collection: ${{ secrets.IA_COLLECTION }}

  upload:
    name: Upload
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [archive]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: upload
        name: Upload
        uses: ./.github/actions/upload
        with:
          artifact: screenshots
          destination: latest-screenshots
          s3-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket-name: ${{ secrets.AWS_BUCKET_NAME }}

  mosaic:
    name: Create JPG mosaic
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [archive]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - uses: actions/download-artifact@v3
        with:
          name: screenshots
          path: ./_input

      - id: mosaic
        name: Mosaic
        run: pipenv run newshomepages-mosaic jpg -i ./_input -o ./_dist
        shell: bash

      - id: save
        name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: mosaics
          path: _dist
          if-no-files-found: error

  discord:
    name: Post to Discord
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [mosaic,upload]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install Python dependencies
        uses: ./.github/actions/install

      - id: discord
        name: Discord
        uses: ./.github/actions/discord
        with:
          bot-token: ${{ secrets.DISCORD_BOT_TOKEN }}
          command: bundle ${{ inputs.bundle }}

  # tweet:
  #   name: Post to Twitter
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   needs: [mosaic,upload]
  #   steps:
  #     - id: checkout
  #       name: Checkout
  #       uses: actions/checkout@v3

  #     - id: tweet
  #       name: Tweet
  #       uses: ./.github/actions/tweet
  #       with:
  #         consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
  #         consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  #         access-token-key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
  #         access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
  #         command: bundle ${{ inputs.bundle }}

  # telegram:
  #   name: Post to Telegram
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   needs: [mosaic,upload]
  #   steps:
  #     - id: checkout
  #       name: Checkout
  #       uses: actions/checkout@v3

  #     - id: telegram
  #       name: Telegram
  #       uses: ./.github/actions/telegram
  #       with:
  #         api-key: ${{ secrets.TELEGRAM_API_KEY }}
  #         command: bundle ${{ inputs.bundle }}
