name: 'Archive: U.S. left wing'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *

jobs:
  archive-bundle:
    name: Archive bundle
    uses: ./.github/workflows/reusable-archive-bundle.yaml
    with:
      bundle: us-left-wing
    secrets: inherit