name: 'Archive: U.S. right wing'

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *

jobs:
  archive-bundle:
    name: Archive bundle
    uses: ./.github/workflows/reusable-archive-bundle.yaml
    with:
      bundle: us-right-wing
    secrets: inherit
